### ISSUE TITLE
Add "jump back" function

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-go-to-definition#2]
It would be nice to be able to return to the previous position after jumping to a definition.

I was thinking of following vim convention for the shortcut (vim uses <kbd>Ctrl</kbd> + <kbd>o</kbd>, but in the browser environment <kbd>Alt</kbd> + <kbd>o</kbd> might be a better default as the former often is used to trigger "open website from file" action). I hope to find som time to implement this next month. In the meantime I'm open to sugestions.

**Comment by cocoaaa** [comment]
This would be very useful!

**Comment by krassowski** [comment]
I've just published 0.1.4 version, adding this functionality.

I would appreciate if anyone interested could test if it works for them!

**Comment by cocoaaa** [comment]
@krassowski  I upgraded to version 0.1.4 today, so far it's been working well.  Thanks!
