### ISSUE TITLE
Hi is there a go to definition extension for jupyter notebook?

### ISSUE THREAD

**Issue by yuanqingye** [krassowski/jupyterlab-go-to-definition#23]
or that extension only apply to jupyter lab?

**Comment by krassowski** [comment]
Yes, this is JupyterLab only extension. I am not aware of jupyter notebook extension equivalent. In theory one could build upon jupyter-lsp from [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) but probably a better way would be to migrate to JupyterLab (if there is anything stopping you from migrating, I recommend you open an issue in JupyterLab repository so it can be addressed).
