### ISSUE TITLE
Cursor disappears when using safari on Macos.

### ISSUE THREAD

**Issue by wtbsw** [krassowski/jupyterlab-go-to-definition#3]
I have used this extension on mac. When this extension enabled, the cursor can't display in edit mode only on safari, both ok on chrome and Firefox.
    
<img width="1247" alt="default" src="https://user-images.githubusercontent.com/14332504/53151732-e0b5a500-35ee-11e9-904b-c4a79e8ec003.png">

<img width="1245" alt="default" src="https://user-images.githubusercontent.com/14332504/53151871-1c506f00-35ef-11e9-9b29-338718e5b7a0.png">

    Thank you for your helping.

**Comment by nesat** [comment]
I have the same problem

**Comment by krassowski** [comment]
Thank you both @wtbsw and @nesat for reporting the problem and narrowing it to Safari on MacOS - this is really helpful!

May I ask you to provide the output (e.g. as a screen-shot) from the developer console of Safari, with the add-on enabled and after an attempt to "jump"?

This screencast: https://youtu.be/hIwrl8kCv04 demonstrates how to open the JavaScript error console in the developer tools of Safari (the interesting part is about one minute long, from beginning to 1:15).

PS. apologies for the delay, I've been busy with my Master thesis (but will be back to open source contributions this Friday).

**Comment by nesat** [comment]
I mentioned in https://github.com/krassowski/jupyterlab-go-to-definition/issues/6 that "go to the definition" does not work but I was mistaken. It works while using the keyboard only.

I checked the console error as you wish, it outputs:
> TypeError: event.getModifierState is not a function. (In 'event.getModifierState(CodeMirrorExtension.modifierKey)', 'event.getModifierState' is undefined)

![Screen Shot 2019-03-12 at 16 58 31](https://user-images.githubusercontent.com/6490604/54206208-eb29d700-44e8-11e9-8f41-1a5ce44c3d83.png)

Here is the gif:
![obufa-y51uz](https://user-images.githubusercontent.com/6490604/54207291-f251e480-44ea-11e9-8c73-1434069fbeba.gif)

**Comment by krassowski** [comment]
Thank you - this helps a lot! A final question, which version of Safari do you use?

[The support table](https://caniuse.com/#feat=keyboardevent-getmodifierstate) shows that `getModifierState` is supported by Safari 10.1+ (released two years ago).

**Comment by nesat** [comment]
Safari version 12.0.3
MacOS Mojave 10.14.3

Thank you for maintaining the repo, it would be great to use your extension 👍

**Comment by krassowski** [comment]
Ok, I found the culprit. Safari does implement `getModifierState` for keyboard events, but not for mouse events. I will need to write a polyfill manually checking metaKey, ctrlKey, altKey etc.

To highlight the line which needs to be changed:

https://github.com/krassowski/jupyterlab-go-to-definition/blob/5700a4b17d7b362b8d012ae95b40164cff660c14/src/editors/codemirror/extension.ts#L47

I should have enough time this weekend to prepare a fix. Again, thanks for sending the details.

**Comment by krassowski** [comment]
Hi there! I've just published a new version which attempts to address the issue that you discovered. Could you re-install the extension (ensuring that you get 0.1.5 version) and let me know if the problem got resolved?

**Comment by nesat** [comment]
I uninstalled the old version and then installed the new one. New version was installed without any error output but it was disabled initially and I can not enable it. I even tried to disable all my other extensions but still I am not able to enable the new version.

Although I could not find out the problem of my existing environment, sharing the extensions may help:

- @jupyterlab/celltags v0.1.4
- @jupyterlab/toc v0.6.0
- @krassowski/jupyterlab_go_to_definition v0.1.5
- @lckr/jupyterlab_variableinspector v0.1.0

Later I tried to create a fresh virtual environment and it works on the new virtual environment. I also tested the cursor and "go to the definition" action, they both work.

**Comment by krassowski** [comment]
Thank you! I will be closing this issue for now.

I have no ideas why the update did not work for you, though if you spot any suspected output in the developer console, please feel free to let me know opening a new issue - I will try to investigate then.

PS. I've just published v0.1.6 version, adding support to `%store magic` - you may try to see if updating with this one works.
