### ISSUE TITLE
Whether plan to support method or class of python module jump like pycharm

### ISSUE THREAD

**Issue by memory-yancy** [krassowski/jupyterlab-go-to-definition#5]
I have see your demo in `README.md`, I notice that below snippets:
```
In [1]: from statistics import mean

In [3]: measurments = [1, 2, 3]
In [4]: mean(measurments)
Out[4]: 2
```

When I click `measurments` in line 4, the cursor will jump to line 3. But when I click `mean` in line 1, whether `jupyterlab-go-to-definition` will jump to `statistics:mean` source code or not ? In other words, whether support features like `Pycharm` code jump while clicking `Crtl + mount left button`, thanks !

FYI: https://www.reddit.com/r/vim/comments/8httzu/pycharmgrade_code_jump_for_python/

**Comment by krassowski** [comment]
I would like to have this feature (I use it all the time in PyCharm), though it would require either writing a backend extension as well or it may need to wait for language server support in JupyterLab (currently in development).

**Comment by krassowski** [comment]
@memory-yancy you may be interested in checking out the latest [v0.5 release](https://github.com/krassowski/jupyterlab-go-to-definition/releases/tag/v0.5.0). It is not exactly the behaviour you asked for, but close enough for me for day-to-day usage.

**Comment by memory-yancy** [comment]
@krassowski It's a good news,  thanks your efforts.

I installed v0.5 release, but it does not work. I see some errors in console, reporting 404, see:   https://img.vim-cn.com/cc/ee1af13bdcbfbed9ef2bbd3986c69bc4c19110.png  (Sorry, I'm not familiar with frontend fully)

I debug it, API `/api/contents/<path:path>` is ok if path is complete, e.g.: http://127.0.0.1:8888/api/contents/opt/conda/lib/python3.6/subprocess.py  Any ideas or I miss something else?
```
root@asus:/opt/conda# /opt/conda/bin/jupyter-labextension  list
JupyterLab v1.0.0
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @krassowski/jupyterlab_go_to_definition v0.5.0  enabled  OK
root@asus:/opt/conda# /opt/conda/bin/jupyter-lab --version
1.0.0
root@asus:/opt/conda# /opt/conda/bin/jupyter-notebook  --version
5.7.8
root@asus:/opt/conda# node --version
v10.0.0
root@asus:/opt/conda# npm --version
5.6.0
```

**Comment by krassowski** [comment]
You might have missed this paragraph in the linked release info:
> Note: only files reachable by JupyterLab can be opened (which is limited due to security reasons, however, may be worked around in the future versions).

The files of subprocess python module (even if correctly resolved by the kernel) are not simply possible to be opened in JupyterLab as those are outside of the starting directory.

I did work around that, but did not publish it before due to #9 and #10. But as it seems that you are willing to test it (and it's always better to have some feedback) I've just published v0.5.1 which includes the workaround. Mind you, tested with Python 3.7 only. It uses following (experimental) design:

> - create symbolic links in a hidden folder, e.g. .jupyter-symlinks and open the file using this link:
>     - easy on Linux, what about Windows?
>     - read and write possible as long as the user has the rights (which is fine)
>     - use of symlinks was also suggested in https://github.com/jupyterlab/jupyterlab/issues/6351

See more: https://github.com/krassowski/jupyterlab-go-to-definition/wiki

**Comment by krassowski** [comment]
After looking at the image again it seems that there must have been an error in the server-side paths resolution... Apologies for that, I misinterpreted some of the tracebacks. I published 0.5.2 which adds a `console.error` message before falling back to guessing the paths for easier debugging if you try again now, we could learn more about the issue that you're having.

Thanks for your feedback!

**Comment by memory-yancy** [comment]
I have tested v0.5.2 is ok :+1:  `from a import b` or `from a.b import c` do work on module `a` or `a.b`, about function definition maybe it should be on the way, looking forward to your good news and LSP suppored in JupyterLab!

I understood your design with the help of wiki and devtools, I think the critical code is:
```
    jump_to_cross_file_reference(context, cell_of_origin_analyzer) {
        let potential_paths = cell_of_origin_analyzer.guessReferencePath(context);
        if (this.cwd) {
            let prefixed_with_cwd = potential_paths.map(path => this.cwd + '/' + path);
            potential_paths = prefixed_with_cwd.concat(potential_paths);
        }
        let code = cell_of_origin_analyzer.referencePathQuery(context);
        if (cell_of_origin_analyzer.supportsKernel && this.kernel && code) {
            cell_of_origin_analyzer.requestReferencePathFromKernel(code, this.kernel, msg => this.handle_path_from_kernel(msg, potential_paths));
        }
        else {
            // if kernel is not available, try use the guessed paths
            // try one by one
            for (let path of potential_paths) {
                this.try_to_open_document(path);
            }
        }
    }
```
I will close it since this features have been met my requirements in usage. Thank you again for your efforts ！

**Comment by krassowski** [comment]
Just FYI, version 0.6 has jumping to symbols (functions, methods, classes) implemented. Clicking on `mean` from your statistics example should now open statistics.py and scroll to the mean definition.
