### ISSUE TITLE
Does not work on MacOS Safari

### ISSUE THREAD

**Issue by nesat** [krassowski/jupyterlab-go-to-definition#6]
Neither alt + click nor alt + ctrl + B does not work on MacOS Safari. Furthermore it leads other problems which makes the notebook unusable https://github.com/krassowski/jupyterlab-go-to-definition/issues/3#issue-412786513

**Comment by krassowski** [comment]
I appreciate that you reported this issue and understand why you may think of it as a separate problem.

I believe that there is a common technical culprit for both this and #3, thus please allow me to mark this one as a duplicate to highlight #3 as preferred for further discussion.

**Comment by krassowski** [comment]
Closing, as resolved in #3. Thanks or reporting @nesat!
